[project]
name = "zapfiles"
version = "2.0.0"
description = "A secure file transfer tool that ensures the privacy of your data through end-to-end encryption."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "colorama>=0.4.6",
    "cryptography>=45.0.4",
    "prettytable>=3.16.0",
    "requests>=2.32.4",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "nuitka>=2.7.10",
    "pre-commit>=4.2.0",
    "pyright[nodejs]>=1.1.402",
    "ruff>=0.12.0",
]
